Name : Godase Sanika

1. Calculate the total revenue generated by two product categories in a store 
Input
import numpy as np

# Revenue data for two categories
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800, 600])

# Calculate total revenue
total_revenue = category1_revenue + category2_revenue

# Print the result
print("Total Revenue:", total_revenue)

Output 

Total Revenue: [ 950 1300 1500 1150]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2. Calculate the profit made by a company 

 Input: 

import numpy as np

# Revenue and expenses data
revenue = np.array([10000, 12000, 11000, 10500])
expenses = np.array([4000, 5000, 4500, 4800])

# Calculate profit
profit = revenue - expenses

# Print the result
print("Profit:", profit)

Output : Profit: [6000 7000 6500 5700]

